language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run build:css

deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app: trll
